# Generated by Django 3.2.5 on 2021-07-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('date', models.CharField(default='2000-12-30', max_length=122)),
                ('time', models.CharField(default='9:00 AM', max_length=122)),
                ('urgency', models.CharField(max_length=122)),
                ('apptype', models.CharField(default='upcoming', max_length=122)),
                ('description', models.CharField(max_length=400)),
                ('created_by', models.CharField(default='admin', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122, unique=True)),
                ('email', models.CharField(max_length=122, unique=True)),
                ('occupation', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=122)),
                ('is_active', models.BooleanField(default=True)),
                ('is_loggedIn', models.BooleanField(default=False)),
            ],
        ),
    ]
