# Generated by Django 3.1.7 on 2021-07-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='2000-12-30', max_length=122),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='9:00 AM', max_length=122),
        ),
        migrations.AddField(
            model_name='person',
            name='is_loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
