# Generated by Django 3.1.7 on 2021-07-12 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='App.person', to_field='name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.CharField(default='2000-12-30', max_length=122),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(default='9:00 AM', max_length=122),
        ),
        migrations.AddField(
            model_name='person',
            name='is_loggedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=122, unique=True),
        ),
    ]
