# Generated by Django 3.2.5 on 2021-07-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='emails',
            field=models.CharField(default='admin@gmail.com', max_length=400),
        ),
    ]
