# Generated by Django 3.1.7 on 2021-07-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210712_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.CharField(default='admin', max_length=122),
        ),
    ]
